Update gh-actions

diff --git a/.github/workflows/build_python.yml b/.github/workflows/build_python.yml
--- a/.github/workflows/build_python.yml
+++ b/.github/workflows/build_python.yml
@@ -1,71 +1,68 @@
 # Adapted from https://github.com/RalfG/python-wheels-manylinux-build/blob/master/full_workflow_example.yml
-name: Python package build and publish
+name: libmcphase
 
 on:
   push:
+    branches: [main]
+  pull_request:
+    branches: [main]
+    types: [opened, reopened, synchronize]
   release:
-    types: [created]
+    types: [published]
+  workflow_dispatch:
+
+concurrency :
+  group: ${{ github.workflow }}-${{ github.ref == 'refs/head/main' && github.run_number || github.ref }}
+  cancel-in-progress: true
+
+defaults:
+  run:
+    shell: bash -l {0}
 
 jobs:
-  deploy_linux:
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: actions/checkout@v2
-
-    - name: Setup python
-      uses: actions/setup-python@v1
-      with:
-        python-version: 3.8
-
-    - name: Install python dependencies
-      run: |
-       python -m pip install --upgrade pip
-       pip install twine
-
-    - name: Build manylinux wheels
-      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
-      with:
-        python-versions: 'cp27-cp27mu cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38'
-        build-requirements: 'cmake'
-        system-packages: ''
-        package-path: ''
-        pip-wheel-args: '--no-deps'
-
-    - name: Publish wheels to PyPI
-      env:
-        TWINE_USERNAME: __token__
-        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-      run: |
-        twine upload wheelhouse/*-manylinux*.whl
-
-  deploy_windows:
-    runs-on: windows-latest
-
+  build_and_test:
     strategy:
-        matrix:
-            python-version: [ '2.7', '3.5', '3.6', '3.7', '3.8' ]
-
-    name: Python ${{ matrix.python-version }} deployment
-
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+    name: Build and test, ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
     steps:
-    - uses: actions/checkout@v2
-
-    - name: Setup python
-      uses: actions/setup-python@v1
-      with:
-        python-version: ${{ matrix.python-version }}
-        architecture: x64
-
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install setuptools wheel twine
-
-    - name: Build and publish wheels to PyPI
-      env:
-        TWINE_USERNAME: __token__
-        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-      run: |
-        python setup.py bdist_wheel
-        twine upload dist/*
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+      - name: Build wheels
+        uses: pypa/cibuildwheel@v2
+        env:
+          CIBW_BUILD: "cp38-* cp39* cp310-* cp311-* cp312-*"
+          CIBW_SKIP: "*musllinux* *win32* *i686*"
+          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
+          CIBW_BUILD_VERBOSITY: 1
+      - uses: mamba-org/setup-micromamba@v1
+        with:
+          cache-downloads: true
+      - name: Install wheels and run test
+        run: |
+          # set -e makes sure the script fails if any command in the loop fails
+          set -e
+          for pyver in 3.8 3.9 3.10 3.11 3.12
+          do
+            $MAMBA_EXE create -n py$pyver -c conda-forge python=$pyver numpy
+            eval "$($MAMBA_EXE shell activate py$pyver)"
+            python -m pip install wheelhouse/*cp$(echo $pyver | sed s/\\.//)*
+            cd tests
+            python -m unittest
+            cd ..
+          done
+      - uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.os }}_artifacts.zip
+          path: wheelhouse/*
+      #- name: Setup tmate
+      #  if: ${{ failure() }}
+      #  uses: mxschmitt/action-tmate@v3
+      #- name: Publish wheels to PyPI
+      #  if: ${{ github.event_name == 'release' }}
+      #  env:
+      #    TWINE_USERNAME: __token__
+      #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+      #  run: |
+      #    twine upload wheelhouse/*
